hostname LEAF1
no ipv6 forwarding
!
interface eth0
 ip address 10.0.11.2/30
exit
!
interface eth1
 ip address 10.0.21.2/30
exit
!
interface lo
 ip address 2.2.2.2/32
exit
!
router bgp 65101
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 neighbor 10.0.11.1 remote-as 65000
 neighbor 10.0.21.1 remote-as 65000
 !
 address-family ipv4 unicast
  network 2.2.2.2/32
  maximum-paths 2
 exit-address-family
exit
!
end
