hostname SPINE2
no ipv6 forwarding
!
interface eth0
 ip address 10.0.21.1/30
exit
!
interface eth1
 ip address 10.0.22.1/30
exit
!
interface lo
 ip address 1.1.1.2/32
exit
!
router bgp 65000
 bgp router-id 1.1.1.2
 no bgp ebgp-requires-policy
 neighbor 10.0.21.2 remote-as 65101
 neighbor 10.0.22.2 remote-as 65102
 !
 address-family ipv4 unicast
  network 1.1.1.2/32
 exit-address-family
exit
!
end
